export const FETCH_FURNITURE_DATA_REQUEST = "FETCH_FURNITURE_DATA_REQUEST";
export const FETCH_FURNITURE_DATA_SUCCESS = "FETCH_FURNITURE_DATA_SUCCESS";
export const FETCH_FURNITURE_DATA_FAILURE = "FETCH_FURNITURE_DATA_FAILURE";
export const FETCH_FURNITURE_DATA_CANCEL = "FETCH_FURNITURE_DATA_CANCEL";
